# The Proceedings of the 1st International Conference on Business, Management and Information Systems 2019 (ICBMIS 2019)

name = "The Proceedings of the 1st International Conference on Business, Management and Information Systems 2019 (ICBMIS 2019)"
license = "GPL v3+"
licenselink = ""
description = ""
homepage = "https://www.icbmis-utb.org/"
tags = ["Poceedings", "ICBMIS 2019"]
features = ["proceedings", "publishing", "academic", "responsive"]
min_version = "0.70.0"

authors = [
  {name = ""},
  {name = ""}
]

[original]
  name = "The Proceedings of the 1st International Conference on Business, Management and Information Systems 2019 (ICBMIS 2019)"
  homepage = "https://www.icbmis-utb.org/"
  repo = ""
