title = "The Proceedings of the 1st International Conference on Business, Management and Information Systems 2019 (ICBMIS 2019)"
baseURL = "https://www.icbmis-utb.org/"
languageCode = "en-US"
theme = "Health Sciences Theme"

# The site's parameters
[params]
  home = "Home"
  abbreviatedTitle = ""
  description = "The Proceedings of the 1st International Conference on Business, Management and Information Systems 2019 (ICBMIS 2019) is an open-access, peer-reviewed academic conference proceedings published by the UTB School of Business, Universiti Teknologi Brunei. This Proceedings, which is published annaualy encourages works in the fields of Accounting, Business, Management, Information Systems, and Economics."
  favicon = "img/favicon.png"
  mirrorfor = ""
  eISBN = "978-99917-919-5-1"
    
  ## Publisher Information
  publisher = {name = "Universiti Teknologi Brunei", city = "Gadong A", state = "Bandar Seri Begawan,", country = "Brunei Darussalam"}
  publisherjournalabbreviation = ""
  subjects = ["Business", "Management", "Information Systems"]
  crossmark_enabled = false
  
  ## Homepage image. Different sizes can be used to provide responsiveness.
  homepageimageset = [{img = "img/homepage_480w.jpg", width = "480w", maxwidth = "800px"},
    {img = "img/homepage_960w.jpg", width = "960w", maxwidth = "1440px"},
    {img = "img/homepage_1920w.jpg", width = "1920w", maxwidth = ""}]
  homepageimagefallback = "img/homepage_960w.jpg"
  homepageimagealt = "Neurons artwork homepage image. CC0 Geralt/Pixabay id-582054"
  
  lenslogo = "img/lens-journal-logo.png"
  
  ## Set current issue or leave blank and the most recent issue will be used.
  currentissuepath = ""
  
  twittercard = "summary_large_image"
  twitterhandle = ""
  socialimage = "img/twittercard.jpg"
  socialimagealt = ""
  socialdescription = "The Proceedings of the 1st International Conference on Business, Management and Information Systems 2019"
  
  ## Set to true to load libraries from Cloudflare and Bootstrap CDNs where available. Otherwise leave blank.
  useCDN = false
  
  ## Custom blocks for the footer
  customblocks = [{ name = "ISBN Details", content = "ISBN 978-99917-919-5-1 (Electronic)     "},
  {name = "License", content = "This theme is released under the GPL3 license."},
  {name = "Privacy Notice", content = "The only user information collected from this website will be used exclusively for the stated purposes of this journal and will not be made available for any other purpose or to any other party."},
  {name = "Contact Us", content = "Dr Mohamed Saleem Haja Nazmudeen (Dean, UTB School of Business)."}]

  
  
  
  [privacy]
  [privacy.googleAnalytics]
    disable = false
  [privacy.disqus]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
  
  [menu]

    [[menu.main]]
      weight = 2
      name = "Articles"
      url = "current"
    [[menu.main]]
      weight = 3
      name = "Archives"
      url = "article"
     [[menu.main]]
      weight = 4
      name = "About"
      hasChildren = true
    [[menu.main]]
      parent = "About"
      name = "About the Proceedings"
      url = "about/proceedings"
      weight = 5
    [[menu.main]]
      parent = "About"
      name = "Editorial Team"
      url = "about/editorial-team"
      weight = 6
    [[menu.main]]
      parent = "About"
      name = "Abstracting/Indexing"
      url = "about/abstracting-indexing"
      weight = 7
    [[menu.main]]
      parent = "About"
      name = "Contact"
      url = "contact"
      weight = 8

# Output formats
[mediaTypes]
  [mediaTypes."text/ris"]
    suffixes = ["ris"]
  [mediaTypes."text/bib"]
    suffixes = ["bib"]
  [mediaTypes."text/enw"]
    suffixes = ["enw"]
  [mediaTypes."text/latex"]
    suffixes = ["tex"]
    
[outputFormats]
  [outputFormats.galleyPDF]
    baseName = "view-pdf"
    isPlainText = true
    mediaType = "text/html"
    path = ""
  [outputFormats.galleyXML]
    baseName = "view-lens"
    isPlainText = true
    mediaType = "text/html"
    path = ""
  [outputFormats.customlens]
    baseName = "js/customlens"
    isPlainText = true
    mediaType = "application/javascript"
    path = ""
  [outputFormats.localfonts]
    baseName = "css/localfonts"
    isPlainText = true
    mediaType = "text/css"
    path = ""
  [outputFormats.lensfonts]
    baseName = "css/lensfonts"
    isPlainText = true
    mediaType = "text/css"
    path = ""
  [outputFormats.exportris]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "text/ris"
    path = ""
  [outputFormats.exportbib]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "text/bib"
    path = ""
  [outputFormats.exportenw]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "text/enw"
    path = ""
  [outputFormats.exportcsljson]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "application/json"
    path = ""

[outputs]
  home = ["HTML", "customlens", "localfonts", "lensfonts"]
  page = ["html", "galleyPDF", "galleyXML", "exportris", "exportenw", "exportbib", "exportcsljson" ]

[taxonomies]
  keyword = "Business, Management and Information Systems"
